# Application name
spring.application.name=task-webflux

# ===============================
# R2DBC (Reactive MySQL) Config
# ===============================
spring.r2dbc.url=r2dbc:mysql://localhost:3306/taskmanager
spring.r2dbc.username=root
spring.r2dbc.password=60790921

# ===============================
# Logging
# ===============================
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.io.r2dbc.mysql=DEBUG
